// Static fallback content used when Supabase is not configured.
// Keeps the public site fully functional in dev/preview environments without
// requiring a live database.

import type { Project, Section, Service, SiteSettings, Testimonial } from "@/lib/supabase/types"

export const defaultSiteSettings: SiteSettings = {
  id: "default",
  brand_name: "Abid Ali",
  tagline: "Custom CMS, Web & Browser Extensions",
  bio: "I help founders and product teams turn ambiguous ideas into shipped, measurable software — from custom CMS platforms to Chrome extensions and end-to-end web apps.",
  email: "admin@abidali.vip",
  phone: "+39 3927035373",
  location: "Italy · Remote worldwide",
  avatar_url: "/images/abid-formal.jpg",
  resume_url: null,
  upwork_url: "https://www.upwork.com/freelancers/~01c94e6af3f2725140",
  github_url: null,
  linkedin_url: null,
  twitter_url: null,
  available_for_work: true,
  hourly_rate: "$45/hr",
  primary_color: "#2563eb",
  avatar_position: "center",
  updated_at: new Date().toISOString(),
}

const now = new Date().toISOString()

export const defaultServices: Service[] = [
  {
    id: "svc-cms",
    slug: "cms",
    title: "Custom CMS Development",
    tagline: "Editorial control without the WordPress tax",
    description:
      "Tailored content management systems that match your real workflow. Multi-tenant, role-based, headless or coupled — built to be a joy for editors and a breeze for developers.",
    icon: "database",
    features: [
      "Role-based access control",
      "Live preview",
      "Versioning & rollback",
      "Custom field types",
      "API + webhooks",
      "Multi-language support",
    ],
    starting_price: "from $1,500",
    delivery_time: "2–4 weeks",
    position: 0,
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-web",
    slug: "web",
    title: "Full-Stack Web Apps",
    tagline: "From idea to production with proof points",
    description:
      "Production-grade web applications with Next.js, TypeScript, Postgres and a tasteful eye for UX. I ship measurable outcomes — not landing pages dressed up as dashboards.",
    icon: "code",
    features: [
      "Next.js / React 19",
      "TypeScript end-to-end",
      "Postgres + Prisma/Supabase",
      "Auth, payments, file upload",
      "Analytics & observability",
      "CI/CD on Vercel/Fly.io",
    ],
    starting_price: "from $2,500",
    delivery_time: "3–6 weeks",
    position: 1,
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-chrome",
    slug: "chrome-extensions",
    title: "Chrome Extensions",
    tagline: "Workflows that live where your users already are",
    description:
      "High-impact browser extensions that scrape, automate, augment or analyse. From LinkedIn outreach helpers to in-page co-pilots — Manifest V3, secure by default.",
    icon: "chrome",
    features: [
      "Manifest V3",
      "OAuth + secure storage",
      "Background workers",
      "Content script overlays",
      "Stripe-billed paid tiers",
      "Chrome Web Store launch",
    ],
    starting_price: "from $900",
    delivery_time: "1–3 weeks",
    position: 2,
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "svc-auto",
    slug: "automation",
    title: "Custom Automation & Scripts",
    tagline: "Boring work, automated. Quickly.",
    description:
      "One-off Python or Node scripts, scheduled jobs, scrapers, AI agents, internal tools — the unglamorous code that compounds your team's leverage.",
    icon: "globe",
    features: [
      "Web scraping at scale",
      "LLM-powered agents",
      "Stripe & QuickBooks plumbing",
      "Spreadsheet/Notion sync",
      "Cron + queue workers",
      "Slack & email triggers",
    ],
    starting_price: "from $300",
    delivery_time: "days, not weeks",
    position: 3,
    published: true,
    created_at: now,
    updated_at: now,
  },
]

export const defaultProjects: Project[] = [
  {
    id: "p-linkreach",
    slug: "linkreach",
    title: "LinkReach — LinkedIn outreach extension",
    tagline: "A Chrome extension that turns LinkedIn into a CRM",
    summary:
      "Built for a B2B agency in Berlin. LinkReach overlays an outreach inbox on top of LinkedIn so SDRs can sequence, track and reply without leaving the page.",
    body:
      "LinkReach started as a small \"saved replies\" helper and grew into a full pipeline view. The hardest parts were keeping pace with LinkedIn's frequent DOM changes and shipping a Manifest V3 background worker that survives restarts. Outcome: 4 SDRs replaced two SaaS tools and reclaimed ~6 hours each per week.",
    cover_image: "/images/review-dashboard.png",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["Chrome MV3", "TypeScript", "React", "Supabase", "Stripe"],
    category: "Chrome Extension",
    client: null,
    industry: "B2B SaaS",
    year: 2025,
    live_url: "https://abidali.vip/linkreach/",
    repo_url: null,
    case_study: true,
    featured: true,
    position: 0,
    published: true,
    metrics: { "Active users": "4 SDRs", "Hours saved per rep": "6/week", "Tools replaced": "2" },
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-donations",
    slug: "donations-payments",
    title: "Custom donation payment system",
    tagline: "Stripe + Squarespace, glued together properly",
    summary:
      "A non-profit needed recurring + one-off donations with country-specific receipts. We built a custom checkout layer on top of Squarespace using Stripe Elements and a tiny serverless backend.",
    body:
      "The client had been losing donors at the Stripe redirect. We replaced the off-site flow with an embedded checkout, added Apple Pay, and emitted IRS-compliant receipts in three currencies. Conversions on the donation page jumped from 1.9% to 4.4%.",
    cover_image: "/images/review-donations.png",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["Stripe", "Next.js", "Squarespace", "Vercel", "Resend"],
    category: "Web App",
    client: null,
    industry: "Non-profit",
    year: 2025,
    live_url: null,
    repo_url: null,
    case_study: true,
    featured: true,
    position: 1,
    published: true,
    metrics: { "Donation conversion": "1.9% → 4.4%", "Avg gift size": "+18%", "Project value": "$1,112" },
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-mass-msg",
    slug: "mass-messaging-dashboard",
    title: "Mass-messaging dashboard",
    tagline: "Send 50,000 messages without setting your IP on fire",
    summary:
      "A multi-tenant dashboard that lets a marketing team queue and throttle outbound campaigns across SMS, email and Telegram with per-channel rate limits and a unified reply inbox.",
    body:
      "Built with Next.js and a Postgres-backed job queue (pg_boss). The trickiest design decision was the unified inbox — we ended up modelling threads as channel-agnostic conversations linked back to a contact graph. The result is a single screen reps can live in.",
    cover_image: "/images/review-dashboard.png",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["Next.js", "Postgres", "pg_boss", "Twilio", "Resend", "Telegram Bot API"],
    category: "Web App",
    client: null,
    industry: "Marketing",
    year: 2024,
    live_url: null,
    repo_url: null,
    case_study: true,
    featured: true,
    position: 2,
    published: true,
    metrics: { "Messages/day": "50,000", "Channels": "3", "Reply SLA": "under 90s" },
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-squarespace-form",
    slug: "squarespace-multistep",
    title: "Multi-step form for Squarespace",
    tagline: "A 7-step intake form that converts",
    summary:
      "A medical clinic on Squarespace needed a HIPAA-aware multi-step intake form with conditional logic, file upload and a CRM hand-off. Native Squarespace forms don't do any of that.",
    body:
      "We injected a React micro-app into the Squarespace page that posts to a serverless backend, encrypts uploads and forwards qualified leads to the clinic's CRM. The form has a 71% completion rate — high for a 7-step, document-heavy flow.",
    cover_image: "/images/review-squarespace.png",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["React", "Squarespace", "Vercel", "Cloudflare R2", "HIPAA-aware"],
    category: "Web App",
    client: null,
    industry: "Healthcare",
    year: 2025,
    live_url: "https://abidali.vip/referral",
    repo_url: null,
    case_study: true,
    featured: true,
    position: 3,
    published: true,
    metrics: { "Completion rate": "71%", "Steps": "7", "Project value": "$1,400" },
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-anatomy",
    slug: "anatomy-3d",
    title: "3D Human Anatomy explorer",
    tagline: "WebGL anatomy for med-school revision",
    summary:
      "An interactive 3D anatomy viewer that lets students isolate systems, label structures and quiz themselves. Built for a private tutor in Italy.",
    body:
      "three.js with a custom GLTF pipeline, plus a quiz layer wired to Supabase for progress tracking. The performance budget was tight — the original model was 240MB; we got it to 22MB without losing fidelity.",
    cover_image: "/images/abid-formal.jpg",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["three.js", "GLTF", "Next.js", "Supabase"],
    category: "Web App",
    client: null,
    industry: "Education",
    year: 2025,
    live_url: "https://abidali.vip/anatomy/",
    repo_url: null,
    case_study: false,
    featured: true,
    position: 4,
    published: true,
    metrics: { "Model size": "240MB → 22MB", "Frame rate": "60fps on mid-tier laptops" },
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-or",
    slug: "operation-theatre",
    title: "3D operation theatre simulator",
    tagline: "A scrubbed-in surgical training environment",
    summary:
      "WebGL operation theatre with interactive instruments and step-based procedure walkthroughs. Used as a study aid for surgical residents.",
    body: null,
    cover_image: "/images/abid-formal.jpg",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["three.js", "React", "GLSL"],
    category: "Web App",
    client: null,
    industry: "Healthcare",
    year: 2025,
    live_url: "https://abidali.vip/Room/",
    repo_url: null,
    case_study: false,
    featured: false,
    position: 5,
    published: true,
    metrics: {},
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-ocr",
    slug: "image-to-text",
    title: "Image-to-Text scanner",
    tagline: "OCR in the browser, no upload required",
    summary:
      "A privacy-first OCR scanner — the entire pipeline runs client-side using Tesseract.js compiled to WASM, so no document ever leaves the user's machine.",
    body: null,
    cover_image: "/images/abid-formal.jpg",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["Tesseract.js", "WASM", "Next.js"],
    category: "Web App",
    client: null,
    industry: null,
    year: 2024,
    live_url: "https://abidali.vip/scanner/",
    repo_url: null,
    case_study: false,
    featured: false,
    position: 6,
    published: true,
    metrics: {},
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-gh",
    slug: "github-generator",
    title: "GitHub repo generator",
    tagline: "Spin up a templated repo from a form",
    summary:
      "A small tool that takes a project description and creates a fully-templated GitHub repo with README, license, CI and labels — useful for teaching workshops.",
    body: null,
    cover_image: "/images/abid-formal.jpg",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["Next.js", "GitHub API", "OAuth"],
    category: "Web App",
    client: null,
    industry: null,
    year: 2024,
    live_url: "https://abidali.vip/github",
    repo_url: null,
    case_study: false,
    featured: false,
    position: 7,
    published: true,
    metrics: {},
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-html",
    slug: "html-builder",
    title: "HTML & code builder",
    tagline: "Drag-and-drop HTML for non-coders",
    summary: "A no-code HTML builder used in coding bootcamps to teach beginners how layout maps to markup.",
    body: null,
    cover_image: "/images/abid-formal.jpg",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["Next.js", "Tiptap", "TailwindCSS"],
    category: "Web App",
    client: null,
    industry: null,
    year: 2024,
    live_url: "https://html.abidali.vip/",
    repo_url: null,
    case_study: false,
    featured: false,
    position: 8,
    published: true,
    metrics: {},
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-ds",
    slug: "datascience",
    title: "Data-science micro-site",
    tagline: "Interactive notebooks for a course",
    summary:
      "A Next.js course site with embedded notebooks and progress tracking, replacing a Notion table-of-contents that wasn't pulling its weight.",
    body: null,
    cover_image: "/images/abid-formal.jpg",
    cover_position: "center" as const,
    cover_fit: "cover" as const,
    gallery: [],
    tech_stack: ["Next.js", "MDX", "Plotly"],
    category: "Web App",
    client: null,
    industry: "Education",
    year: 2024,
    live_url: "https://abidali.vip/datascience",
    repo_url: null,
    case_study: false,
    featured: false,
    position: 9,
    published: true,
    metrics: {},
    created_at: now,
    updated_at: now,
  },
]

export const defaultTestimonials: Testimonial[] = [
  {
    id: "t-wp",
    client_name: "Verified Upwork client",
    client_role: "Founder",
    client_company: null,
    client_avatar: null,
    quote:
      "Abid built a multi-page WordPress site for us in days, not weeks. Calm, fast, exactly what we asked for.",
    rating: 5.0,
    project_value: "$607.50",
    source: "Upwork",
    source_url: "https://www.upwork.com/freelancers/~01c94e6af3f2725140",
    proof_image: "/images/review-wordpress.png",
    proof_image_position: "center" as const,
    featured: true,
    position: 0,
    published: true,
    created_at: now,
  },
  {
    id: "t-don",
    client_name: "Verified Upwork client",
    client_role: "Director",
    client_company: null,
    client_avatar: null,
    quote:
      "Custom donations payment system delivered on time and ahead of spec. Handles edge cases I didn't even think about.",
    rating: 5.0,
    project_value: "$1,112.50",
    source: "Upwork",
    source_url: "https://www.upwork.com/freelancers/~01c94e6af3f2725140",
    proof_image: "/images/review-donations.png",
    proof_image_position: "center" as const,
    featured: true,
    position: 1,
    published: true,
    created_at: now,
  },
  {
    id: "t-dash",
    client_name: "Verified Upwork client",
    client_role: "Head of Growth",
    client_company: null,
    client_avatar: null,
    quote:
      "The mass-messaging dashboard he built has been running for months without a hiccup. Best contractor I've worked with on Upwork.",
    rating: 5.0,
    project_value: "$1,100.00",
    source: "Upwork",
    source_url: "https://www.upwork.com/freelancers/~01c94e6af3f2725140",
    proof_image: "/images/review-dashboard.png",
    proof_image_position: "center" as const,
    featured: true,
    position: 2,
    published: true,
    created_at: now,
  },
  {
    id: "t-sq",
    client_name: "Verified Upwork client",
    client_role: "Operations Lead",
    client_company: null,
    client_avatar: null,
    quote: "Squarespace doesn't do multi-step forms — Abid made it do exactly that. Five stars.",
    rating: 5.0,
    project_value: "$1,400.00",
    source: "Upwork",
    source_url: "https://www.upwork.com/freelancers/~01c94e6af3f2725140",
    proof_image: "/images/review-squarespace.png",
    proof_image_position: "center" as const,
    featured: true,
    position: 3,
    published: true,
    created_at: now,
  },
]

export const defaultSections: Section[] = [
  {
    id: "s-hero",
    type: "hero",
    title: "Hero",
    data: {
      eyebrow: "Available for new work",
      heading: "Custom software, shipped with proof.",
      highlight: "shipped with proof.",
      subheading:
        "I build CMS platforms, full-stack web apps and Chrome extensions for founders who care about outcomes — not slide decks.",
      primary_cta: { label: "See my work", href: "/projects" },
      secondary_cta: { label: "Book a call", href: "/contact" },
    },
    position: 0,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-stats",
    type: "stats",
    title: "By the numbers",
    data: {
      items: [
        { value: "120+", label: "Projects shipped" },
        { value: "30+", label: "Clients worldwide" },
        { value: "100%", label: "Job success on Upwork" },
        { value: "5.0", label: "Avg client rating" },
      ],
    },
    position: 1,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-logos",
    type: "logos",
    title: "Trusted by teams in",
    data: {
      items: ["B2B SaaS", "Healthcare", "Education", "Non-profits", "Fin-tech", "E-commerce"],
    },
    position: 2,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-services",
    type: "services",
    title: "What I do",
    data: {
      eyebrow: "Services",
      heading: "Built like a product, priced like a service",
      subheading: "Four focused offerings. Pick the one that matches the shape of your problem.",
    },
    position: 3,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-projects",
    type: "featured_projects",
    title: "Selected work",
    data: {
      eyebrow: "Case studies",
      heading: "Recent projects with measurable outcomes",
      subheading: "Each one ships with the metric the client cared about — not just a screenshot.",
    },
    position: 4,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-process",
    type: "process",
    title: "How I work",
    data: {
      eyebrow: "Process",
      heading: "A predictable path from \"idea\" to \"in production\"",
      steps: [
        { title: "Discovery call", description: "30-minute call to understand outcomes, constraints and budget. Free." },
        { title: "Scope & quote", description: "Within 48 hours: a fixed quote, milestone breakdown and a Notion plan you can comment on." },
        { title: "Build in slices", description: "Weekly demos against a shared staging URL. You see progress; nothing surprises you at the end." },
        { title: "Ship & support", description: "Production deploy, handover docs and a 14-day support window included on every project." },
      ],
    },
    position: 5,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-tech",
    type: "tech_stack",
    title: "Tools I reach for",
    data: {
      items: ["TypeScript", "Next.js", "React", "Node.js", "Postgres", "Supabase", "Stripe", "Tailwind", "three.js", "Python", "Chrome MV3", "Vercel"],
    },
    position: 6,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-tests",
    type: "testimonials",
    title: "What clients say",
    data: {
      eyebrow: "Reviews",
      heading: "Receipts from real clients",
      subheading: "All Upwork-verified, with original screenshots — not curated quotes.",
    },
    position: 7,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-faq",
    type: "faq",
    title: "Common questions",
    data: {
      items: [
        { question: "How do you price projects?", answer: "Fixed-price for anything I can scope; hourly for ongoing work. You always see the number before we start." },
        { question: "Do you sign NDAs?", answer: "Yes — I'll happily sign a mutual NDA before we get into anything sensitive." },
        { question: "What about the code?", answer: "You own it. I push to a repo you control on day one." },
        { question: "Can you work with my team?", answer: "Yes. I've embedded into product teams as a contractor for sprints up to 6 months." },
      ],
    },
    position: 8,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
  {
    id: "s-cta",
    type: "cta",
    title: "Closing CTA",
    data: {
      heading: "Got a project in mind?",
      subheading:
        "Tell me what you're trying to build. I'll reply within a working day with a sharp opinion and a path forward.",
      primary_cta: { label: "Start a project", href: "/contact" },
      secondary_cta: { label: "View Upwork profile", href: "https://www.upwork.com/freelancers/~01c94e6af3f2725140" },
    },
    position: 9,
    enabled: true,
    page: "home",
    created_at: now,
    updated_at: now,
  },
]
